[package]
name = "sammakkokatedraali_1"
version = "0.1.0"
authors = ["Armelias", "VoxWave"]
edition = "2018"

[dependencies]
piston_window = "0.85.0"
specs = "0.14.3"
nalgebra = "0.16.13"
specs-derive = "0.4.0"